/**************************************************************************

Filename    :   Video_CriHeap.h
Content     :   Video memory allocator for CRI Mana
Created     :   June 4, 2008
Changed    :   March 10, 2026
Authors     :   Maxim Didenko, Vladislav Merker (2008.6.4) [is cri movie 3.50]
                    MonstroFil, Claude(2026.3) [Changed To Cri Mana 2019 From Criware SDK 2.19.03, From Github Author]
                    FINALZ-27980 [To Integration]

Copyright   :   Copyright 2011 Autodesk, Inc. All Rights reserved.
                     Copyright 2026 Final Game Production Inc. All Rights reserved.

TIPS          :  This Version Is Not Stable To Open The New Sample Like GFL2 Exilium .usm
                      (GFL2 Exilium Game Video Has No Crypto, ... Encoding Is VP9?H.264?H.265, Created By Sofdec2 Encoding Wizard) File Cuz It's Has Crash.
                    But Sofdec2 Viewer Can Open It (2.09.02 [For Original SDK 2.19.03] Can Do It).
                    Other .usm (Such PS3 Game Kung Fu Panda 2 .usm File Generated By ScaleformVideoEncoder, Is MPEG1-USMs) File Is Normal.

                    The Reason When Open GFL2 Exilium .usm Video File Is:
                    An unhandled exception occurred at 0x0000000140637401 (in GFxPlayer_D3D11_Release_Static.exe, USE-AFTER-FREE Problem): 0xC0000005:
                    Access violation when reading location 0x0000000000000008.

					Another Problem Is Scaleform Official Named Sample_VP9.usm From CRIWARE Official SDK 2.19.03, Is Same Reason LIke GFL2 Exilium .usm File,
                    It's Crash And USE-AFTER FREE Too.

                    THE TYPICAL REASON OF THIS PROBLEM IS:
					When Open A New Sample Like GFL2 Exilium .usm File, The Video Reader Will Be Created By Criware SDK, But The Video Reader Is NULL,
					... ENDOCING THREADS NUMBER IS 0, ... And When The Video Reader Is Used To Read The Video Data, It Will Cause Access Violation And Crash.

                    Should Be Fix It Is Requirments.

                    This Criware SDK Will Be Removed In Scaleform 5.0 (After 2030) Stable Version, And Change To FFMpeg,
                    FINAL VIDEO(FINAL ENGINE), A SelectaVision HDRVIDEOS Persensation(.264-.268), And More Support Video As Everyone Seen.

Use of this software is subject to the terms of the Autodesk license
agreement provided at the time of installation or download, or which
otherwise accompanies this software in either electronic or hard copy form.

**************************************************************************/

#ifndef INC_GFX_VIDEO_CRIHEAP_H
#define INC_GFX_VIDEO_CRIHEAP_H

#include "GFxConfig.h"
#ifdef GFX_ENABLE_VIDEO

#include "Kernel/SF_MemoryHeap.h"

namespace Scaleform { namespace GFx { namespace Video {

// Register Scaleform memory heap as the allocator for CRI Mana library.
// Must be called before criMana_Initialize.
void criManaHeap_Register(MemoryHeap* pHeap);

// Unregister the Scaleform memory allocator from CRI Mana.
// Call after criMana_Finalize.
void criManaHeap_Unregister();

}}} // Scaleform::GFx::Video

#endif // GFX_ENABLE_VIDEO

#endif // INC_GFX_VIDEO_CRIHEAP_H
